import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex bg-gray-200">
        {/* Left Sidebar */}
        <Sidebar />

        {/* Feed/Posts */}
        {/* Right Sidebar */}
      </main>
    </>
  );
}
