import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import { getSession } from "next-auth/react";
import { GetServerSideProps } from "next";
import { Session } from "next-auth";
import LogIn from "@/components/LogIn";

type HomePageProps = {
  session: Session;
};

export default function Home({ session }: HomePageProps) {
  if (!session) return <LogIn />;

  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex bg-gray-200">
        {/* Left Sidebar */}
        <Sidebar />

        {/* Feed/Posts */}
        {/* Right Sidebar */}
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  return {
    props: {
      session
    }
  };
};
