import React from "react";
import Image from "next/image";
import Head from "next/head";
import { signIn } from "next-auth/react";

type LogInProps = {};

const LogIn: React.FC<LogInProps> = () => {
  return (
    <>
      <Head>
        <title>Google LogIn Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/facebook-round-line-icon.svg" />
      </Head>
      <div className="flex flex-col items-center mx-auto mt-32">
        <Image
          src={"/Google-logo.png"}
          priority
          width={240}
          height={240}
          style={{ height: "auto", width: "auto" }}
          alt="Facebook Symbol, Facebook Logos Within A White Square"
        />
        <a
          onClick={() => signIn()}
          className="px-20 py-4 z-10 text-2xl cursor-pointer bg-blue-500 rounded-md text-white"
        >
          LogIn
        </a>
      </div>
    </>
  );
};
export default LogIn;
